name: Terraform Pipeline

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ env.CLIENT_ID }}
          tenant-id: ${{ env.TENANT_ID }}
          subscription-id: ${{ env.SUBSCRIPTION_ID }}
          client-secret: ${{ env.CLIENT_SECRET }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve
        working-directory: ./terraform